project_id = "hzrdpoyxamsptfbgrhru"

[functions.analyze-vibe]
verify_jwt = false

[functions.leaderboard-api]
verify_jwt = false

[functions.submit-vibe]
verify_jwt = false

[functions.analyze-high]
verify_jwt = false